### PR TITLE
feat(Controller): Add EventHandler

### PR DESCRIPTION
**Pull request by the9ball**
## TL;DR

Add EventHandler on Controller.

## Usage

Send metrics or Logging or Other.

### CODE REVIEW

**Comment by the9ball** [comment]
> I think the name IEventHandler is a little too generic, so why not make it clear that it is a Controller event?

I chose a concise name because it is okay to do so since it is closed off within the DFrame.Controller namespace.
If it needs to be fixed, I'll fix it, but if MessagePipe can be used, that might be a better option.

> Since the DFrame.Controller project includes [MessagePipe](https://github.com/Cysharp/MessagePipe), why not use MessagePipe rather than introducing a new event handler?

I see. It seems like a promising approach. I will experiment with it.

**Comment by the9ball** [comment]
I noticed that there is no documentation for MessagePipe in this repository. I am hesitant to use undocumented features, and I couldn't figure out how to use it after a brief look.
(Isn't it common for undocumented features to be deprecated?)

It would be helpful if there was documentation on how to use it. Do you have any plans to provide it?

**Comment by hadashiA** [comment]
> I  am hesitant to use undocumented features, and I couldn't figure out how to use it after a brief look.

It would not be necessary to explain all the features of MessagePipe.

On the library side, implement `IPublisher<TEvent>` and publish the event. 
Then, perhaps all the user has to do is, provide a type that implements `ISubscriber<TEvent>`. It would not be much different from implementing `IEventHandler` and registering it in a DI container. In fact, it is a bit easier.

I think it would be sufficient to explain this and then provide a link to MessagePipe. What do you think?

> I chose a concise name because it is okay to do so since it is closed off within the DFrame.Controller namespace.

Well, yes, but namespace is usually omitted, so I thought it would be better to be self-explanatory in the type name when looking at the DI configuration.

**Comment by the9ball** [comment]
> On the library side, implement IPublisher<TEvent> and publish the event.
> Then, perhaps all the user has to do is, provide a type that implements ISubscriber<TEvent>. It would not be much different from implementing IEventHandler and registering it in a DI container. In fact, it is a bit easier.

I misunderstood that I should use the existing IPublisher<TEvent>.
I see that the plan is to add a new IPublisher<TEvent> to DFrameControllerExecutionEngine.
I will try it out.

> It would not be necessary to explain all the features of MessagePipe.
> I think it would be sufficient to explain this and then provide a link to MessagePipe. What do you think?

I think it would be a good idea to provide example of the types that are actually used, and perhaps provide a brief overview of how to use them.
I agree that a link to MessagePipe would be sufficient for detailed usage information.

> Well, yes, but namespace is usually omitted, so I thought it would be better to be self-explanatory in the type name when looking at the DI configuration.

I believe that the only time we touch the IEventHandler type is when defining the implemented type and when registering the service. If the name is a problem in those cases, we could consider using an alias or nesting the namespace one level deeper.

However, since we are likely to use MessagePipe, this seems like a moot point.

**Comment by the9ball** [comment]
re-implemented by MessagePipe : #47

**Pull request closed without merging**
